services:
  accounts:
    image: "sauravdocker321/accounts:s2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - phoenixBank
  loans:
    image: "sauravdocker321/loans:s2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - phoenixBank
  cards:
    image: "sauravdocker321/cards:s2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - phoenixBank
networks:
  phoenixBank:
    driver: "bridge"